---
title: "R Notebook"
output: html_notebook
---

```{r}
library(rpart)
library(rpart.plot)
library(tidyverse)
library(janitor)

library(rpart)
library(rpart.plot)


titanic_set <- read_csv('data/titanic_decision_tree_data.csv')

shuffle_index <- sample(1:nrow(titanic_set))

# shuffle the data so class order isn't in order - need this for training/testing split later on 
titanic_set <- titanic_set[shuffle_index, ]
```

```{r}
titanic_set <- titanic_set %>% 
  filter(survived == "1") %>% 
  drop_na(age) %>% 
  mutate(age_status = ifelse(age<16,"child","adult")) %>% 
  select(-c(X1, passenger_id, name, ticket, fare, cabin)) %>% 
  mutate(sib_sp =  if_else(sib_sp == 1, "yes", "no")) %>% 
  mutate(survived = if_else(survived == 1, "yes", "no")) %>% 
   mutate_if(is_character, as_factor) %>%
  clean_names()
  


titanic_set


```
```{r}
split1 <- titanic_set %>% 
  select(pclass, sex, age, sib_sp, survived)

split2 <- titanic_set %>% 
  select(parch, embarked, age_status, survived )
```

```{r}
library(ggfortify)
library(GGally)

```

```{r}
ggpairs(split1, progress = FALSE)
```

```{r}
ggpairs(split2, progress = FALSE)
```

```{r}
 #get how many rows we have in total to work out the percentage
n_data <- nrow(titanic_set)

# create a test sample index
test_index <- sample(1:n_data, size = n_data * 0.2)

# create test set
titanic_test  <- slice(titanic_set, test_index)

# create training set
titanic_train <- slice(titanic_set, -test_index)
```


#build a decision tree
```{r}

titanic_fit <- rpart(
  formula = survived ~ ., 
  data = titanic_train,
  method = "class")

```

```{r}
rpart.plot(titanic_fit,
           yesno = 2,
           fallen.leaves = TRUE,
           faclen = 6, 
           digits = 4)
           
```

