---
title: "R Notebook"
output: html_notebook
---
Load tidyverse and data into R studio
```{r}
library(tidyverse)
books <- read_csv("data/books.csv")

#have a look at the data, what are we dealing with 
glimpse(books) #provides a full breakdown on the table this with the environment window will provide a full 

class(books)
```

```{r}

#lets get a count of the number of missing values
is.na(books)
sum(is.na(books))

```

```{r}
#which columns are those missing values in?

summary(books)

#can be seen that there are 12 variables with 8472 observations that have some 
#na's and starnge values where 0 is probably not the true value

```
```{r}
#use drop_na() function to kill thrm off - but will save subset in new variable first 

books_removed_nas <- drop_na(books)

summary(books_removed_nas)

#no more missing values

```

```{r}
#min number of pages =0?? lets run a script to find them and replace their values - first need to find how many books have 0 pages


zero_num_pages <- filter(books, num_pages == 0) 
zero_num_pages
 
#states there are 42 books that have a zero as the number of pages - need to figure out should we drop or impute - reckon we drop them but not sure how to make this conclusion.

mutate(num_pages_imputed = 

# min number of average rating  & text reviews 0?? - need to have a look at these
#

zero_average_rating <- filter(books, average_rating == 0) 
zero_average_rating

# 19 have a average rating of zero

zero_text_reviews_count <- filter(books, text_reviews_count == 0)
zero_text_reviews_count

#text_review_count is a lot more in that it is 458.
#again need to figure out if we should impute - ask on Monday 

```

